-- BlueBubbles server database schema backup.
--
-- This file is documentation/a backup only.  The application does not load or
-- execute it, and adding it does not change an existing PostgreSQL database.
-- It creates the tables and indexes required by the current server code, but
-- intentionally contains no user, message, or encryption-key data.

BEGIN;

CREATE TABLE IF NOT EXISTS users (
    "userID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash CHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS encryption_keys (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type TEXT NOT NULL,
    scope_id UUID NOT NULL,
    wrapped_key BYTEA NOT NULL,
    key_version INTEGER NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rotated_at TIMESTAMP,
    UNIQUE (scope_type, scope_id, key_version)
);

CREATE TABLE IF NOT EXISTS messages (
    message_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id INTEGER NOT NULL REFERENCES users("userID") ON DELETE CASCADE,
    recipient_id INTEGER NOT NULL REFERENCES users("userID") ON DELETE CASCADE,
    -- Retained for legacy, pre-encryption messages. New messages store an empty value.
    message_content TEXT NOT NULL DEFAULT '',
    sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    body_ciphertext BYTEA,
    encryption_nonce BYTEA,
    encryption_key_id INTEGER REFERENCES encryption_keys(id),
    encryption_version INTEGER,
    encrypted_at TIMESTAMP,
    message_type TEXT NOT NULL DEFAULT 'text' CHECK (message_type IN ('text', 'file')),
    attachment_uuid UUID
);

CREATE TABLE IF NOT EXISTS chat_contacts (
    "userID" INTEGER NOT NULL REFERENCES users("userID") ON DELETE CASCADE,
    contact_id INTEGER NOT NULL REFERENCES users("userID") ON DELETE CASCADE,
    added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("userID", contact_id),
    CHECK ("userID" <> contact_id)
);

CREATE INDEX IF NOT EXISTS encryption_keys_active_scope_lookup_idx
    ON encryption_keys (scope_type, scope_id, status, key_version DESC, id DESC);

CREATE INDEX IF NOT EXISTS messages_conversation_lookup_idx
    ON messages (sender_id, recipient_id, sent_at, message_id);

CREATE UNIQUE INDEX IF NOT EXISTS messages_attachment_uuid_unique_idx
    ON messages (attachment_uuid) WHERE attachment_uuid IS NOT NULL;

COMMIT;
